map_type: costmap #Map type to use, "voxel" or "costmap".

obstacle_range: 2.5 #The maximum range in meters at which to insert obstacles into the costmap using sensor data.
raytrace_range: 3.0 #The maximum range in meters at which to raytrace out obstacles from the map using sensor data. 

#The footprint of the robot specified in the robot_base_frame coordinate frame as a list in the format: [ [x1, y1], [x2, y2], ...., [xn, yn] ]. The footprint specification assumes the center point of the robot is at (0.0, 0.0) 
#footprint: [[-0.23,-0.23],[-0.23,0.23], [0.23, 0.23], [0.23,-0.23]]
robot_radius: 0.25 # 0.2
#inflation_radius: 0.1

resolution: 0.02 #The resolution of the map in meters/cell. 
cost_scaling_factor: 10.0 #A scaling factor to apply to cost values during inflation. 
transform_tolerance: 0.8 # 0.6
#observation_source: A list of observation source names separated by spaces
#	/sensor_frame: The frame of the origin of the sensor
#	/topic		 : The topic on which sensor data comes in for this source.
#	data_type    : The data type associated with the topic.
#	clearing     : Whether or not this observation should be used to clear out freespace
#	marking      : Whether or not this observation should be used to mark obstacles.

#observation_sources: scan
#scan: {sensor_frame: base_link, topic: /scan, data_type: LaserScan, clearing: true, marking: true}

plugins: 
      - {name: static_layer, type: "costmap_2d::StaticLayer", output: "screen"}
#      - {name: undefined_obstacle_layer, type: "costmap_2d::SemanticObstacleLayer", output: "screen"}
#      - {name: human_obstacle_layer, type: "costmap_2d::SemanticObstacleLayer", output: "screen"}
#      - {name: semantic_inflation_layer, type: "costmap_2d::SemanticInflationLayer", output: "screen"} 
      - {name: human_obstacle_layer, type: "costmap_2d::SemanticObstacleLayer", output: "screen"}
      - {name: semantic_inflation_layer, type: "costmap_2d::SemanticInflationLayer", output: "screen"} 

undefined_obstacle_layer:
   observation_sources: scan
   scan: {sensor_frame: base_link, topic: /tracking/masked_targets_scan, data_type: LaserScan, clearing: true, marking: true, obstacle_range: 5, raytrace_range: 5}
   cost: 254 # cost value between 0~254: 0-FREE_SPACE, 254-LETHAL_OBSTACLE

human_obstacle_layer:
   observation_sources: scan #/tracking/targets_scan
   scan: {sensor_frame: base_link, topic: /scan, data_type: LaserScan, clearing: true, marking: true, obstacle_range: 5, raytrace_range: 5}
   cost: 254 # cost value between 0~254: 0-FREE_SPACE, 254-LETHAL_OBSTACLE

semantic_inflation_layer:
  inflation_radius: 0.3 # 0.3
#More information at http://wiki.ros.org/costmap_2d and http://wiki.ros.org/costmap_2d/flat 
