# Dockerfile to build custom image for melodic with nvidia gpu
ARG ros_distro=melodic

FROM osrf/ros:$ros_distro-desktop-full

ARG ros_distro=melodic
ENV ROS_DISTRO=$ros_distro
ARG DEBIAN_FRONTEND=noninteractive

# Install packages
RUN apt-get update && apt-get upgrade -y && apt-get install -q -y --no-install-recommends sudo \
    python-pip \
    curl \
    ros-$ros_distro-navigation \
    ros-$ros_distro-eband-local-planner \
    ros-$ros_distro-hector-slam \
    ros-$ros_distro-cv-bridge \
    wget \
    cmake \
    libopenmpi-dev \
    python3-dev \
    zlib1g-dev \
    make \
    gcc \
    libgtk-3-dev \
    libwebkitgtk-dev \
    libwebkitgtk-3.0-dev \
    freeglut3 \
    freeglut3-dev \
    python-gst-1.0 \
    python3-gst-1.0 \
    libglib2.0-dev \
    ubuntu-restricted-extras \
    libgstreamer-plugins-base1.0-dev 

# Install sublime
RUN apt-get install -y software-properties-common apt-transport-https
RUN wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
RUN echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
RUN apt-get update && apt-get install -y sublime-text

# Install terminator
RUN apt-get install -y terminator 

# Force install of missing dependencies
RUN apt-get -y -f install && \
    rm -rf /var/lib/apt/lists/

# Copy bashrc
COPY docker/config/bashrc /root/.bashrc

# install python3.7
RUN /bin/bash -c 'mkdir /root/AltPythonVersions && cd /root/AltPythonVersions && \
                wget https://www.python.org/ftp/python/3.7.16/Python-3.7.16.tgz && \
                tar xzf Python-3.7.16.tgz && \
                rm Python-3.7.16.tgz && \
                cd Python-3.7.16 && \
                sudo ./configure --enable-optimizations && \
                sudo make altinstall'

#Install virtualenv and create venv
RUN /bin/bash -c 'mkdir /root/venv && cd /root/venv && \
                virtualenv --python=python3.7 py3.7 && \
                source /root/venv/py3/bin/activate'

# Set path to virtualenv
ENV PATH /root/venv/py3.7:$PATH

# Install pybullet-gym
RUN cd /root && git clone https://github.com/benelot/pybullet-gym.git

# copy files to container
COPY . /root/rl_ws/src/ros_pybullet_rl2/
RUN /bin/bash -c 'cp -r /root/rl_ws/src/ros_pybullet_rl2/common/other_packages/* /root/rl_ws/src/ && \
    cp -r /root/rl_ws/src/ros_pybullet_rl2/common/additions_into_pybullet-gym/* /root/pybullet-gym/pybulletgym/envs/'

# make workspace & install dependencies
RUN /bin/bash -c 'echo -e "source /root/venv/py3.7/bin/activate" >> /root/.bashrc && source /root/.bashrc'

# copy dependencies
COPY docker/config/install_dependencies.sh /root/install.sh

# setup entrypoint
COPY docker/config/ros_entrypoint_$ROS_DISTRO.sh /ros_entrypoint.sh 
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
SHELL ["/bin/bash", "-c"]
CMD /bin/bash -c "source ~/.bashrc""