# Dockerfile to build custom image for kinetic with nvidia gpu
ARG ros_distro=kinetic

FROM nvidia/cudagl:11.2.2-base-ubuntu16.04
# FROM osrf/ros:melodic-desktop-full

ARG ros_distro=kinetic
ENV ROS_DISTRO=$ros_distro

ARG DEBIAN_FRONTEND=noninteractive

# remove for integrated graphics
# allow nvidia container toolkit
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics,compute,utility,display

# Install packages
RUN apt-get update && apt-get upgrade -y && apt-get install -q -y --no-install-recommends sudo \
    python-pip \
    curl \
    wget \
    cmake \
    libopenmpi-dev \
    python3-dev \
    zlib1g-dev \
    make \
    gcc \
    libgtk-3-dev \
    libwebkitgtk-dev \
    libwebkitgtk-3.0-dev \
    freeglut3 \
    freeglut3-dev \
    python-gst-1.0 \
    python3-gst-1.0 \
    libglib2.0-dev \
    ubuntu-restricted-extras \
    libgstreamer-plugins-base1.0-dev \
    dbus-x11 \
    mesa-utils

# Install ros kinetic
# setup keys and source.list
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list;

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-$ros_distro-desktop-full \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    python-rosdep \
    python-rosinstall \
    python-vcstools \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init && rosdep update --rosdistro $ros_distro
RUN apt-get update && apt-get -y install -y \
    python-rosinstall \
    ros-$ros_distro-qt-ros \
    ros-$ros_distro-navigation \
    ros-$ros_distro-eband-local-planner \
    ros-$ros_distro-hector-slam \
    ros-$ros_distro-cv-bridge

# Install sublime
RUN apt-get install -y software-properties-common apt-transport-https
RUN wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
RUN echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
RUN apt-get update && apt-get install -y sublime-text

# Install terminator
RUN apt-get install -y terminator 

# Force Install of missing dependencies
RUN apt-get -y -f install

# Copy bashrc
COPY docker/config/bashrc /root/.bashrc

#Install virtualenv and create venv
RUN /bin/bash -c 'mkdir /root/venv && cd /root/venv && \
                virtualenv --python=python3 py3 && \
                source /root/venv/py3/bin/activate'

# Set path to virtualenv
ENV PATH /root/venv/py3:$PATH

# Install pybullet-gym
RUN cd /root && git clone https://github.com/benelot/pybullet-gym.git

# copy files to container
COPY . /root/rl_ws/src/ros_pybullet_rl2/
RUN /bin/bash -c 'cp -r /root/rl_ws/src/ros_pybullet_rl2/common/other_packages/* /root/rl_ws/src/ && \
    cp -r /root/rl_ws/src/ros_pybullet_rl2/common/additions_into_pybullet-gym/* /root/pybullet-gym/pybulletgym/envs/'

# make workspace & install dependencies
RUN /bin/bash -c 'echo -e "source /root/venv/py3/bin/activate" >> /root/.bashrc && source /root/.bashrc'

# copy dependencies
COPY docker/config/install_dependencies.sh /root/install.sh

# setup for terminator
COPY docker/config_${ros_distro}/terminator_config /root/.config/terminator/config

# Make SSH available
EXPOSE 22

# setup entrypoint
COPY docker/config/ros_entrypoint_$ROS_DISTRO.sh /ros_entrypoint.sh 
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
SHELL ["/bin/bash", "-c"]
CMD /bin/bash -c "source ~/.bashrc"