!!python/object/apply:collections.OrderedDict
- - - cliprange
    - 0.2
  - - ent_coef
    - 0.01
  - - gamma
    - 0.99
  - - lam
    - 0.95
  - - learning_rate
    - 0.0001
  - - n_envs
    - 16
  - - n_steps
    - 2048
  - - n_timesteps
    - 1000000.0
  - - nminibatches
    - 4
  - - noptepochs
    - 10
  - - normalize
    - true
  - - policy
    - MlpPolicy
